name: absensi_ruangan
description: Aplikasi absensi dalam ruangan dengan Supabase

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  supabase_flutter: ^2.5.0
  geolocator: ^10.1.0
  image_picker: ^1.1.2
  flutter_map: ^7.0.0
  latlong2: ^0.9.0
  http: ^1.1.0
  intl: ^0.19.0
  provider: ^6.0.5
  lottie: ^3.0.0
  file_picker: ^6.1.1
  path: ^1.8.3
  image: ^4.0.17

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/